steps:
  # Install Node.js
  - name: node:14.16.0
    entrypoint: npm
    args: ["install"]
    dir: /workspace

  # Build the application
  - name: node:14.16.0
    entrypoint: npm
    args: ["run", "build"]
    dir: /workspace

  # Deploy the application to App Engine
  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - --version=0.1.0
      - --project=uplifted-plate-383115
      - --quiet
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1'
      - 'CLOUDSDK_CORE_PROJECT=uplifted-plate-383115'
